// <auto-generated />
using System;
using LandMarkAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;

namespace LandMarkAPI.Data.Migrations
{
    [DbContext(typeof(LandMarkContext))]
    partial class LandMarkContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-preview1-28290")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LandMarkAPI.Domain.Entities.Auth.OAuth", b =>
                {
                    b.Property<int>("OAuthId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Signature");

                    b.Property<string>("Token");

                    b.Property<string>("TokenSecret");

                    b.Property<string>("Verifier");

                    b.HasKey("OAuthId");

                    b.ToTable("OAuths");
                });

            modelBuilder.Entity("LandMarkAPI.Domain.Entities.Person.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int>("OAuthId");

                    b.Property<string>("Surname");

                    b.Property<string>("Username");

                    b.Property<string>("Usernsid");

                    b.HasKey("PersonId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
